# Generated by Django 4.2.2 on 2023-08-10 05:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.BooleanField(default=False)),
                ('image', models.FileField(upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence_number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('block', models.BooleanField(default=True)),
                ('description', ckeditor.fields.RichTextField(max_length=999)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
