# Generated by Django 4.2.2 on 2023-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimagemodel',
            name='sequence_number',
            field=models.IntegerField(),
        ),
    ]
